### ISSUE TITLE
Could you offer a small data set for test?

### ISSUE THREAD

**Issue by Zheng392** [ChenJingyuan91/ACF#1]
Could you offer a small data set for test?

**Comment by DoubleYing** [comment]
do you have the dataset now?

**Comment by ConanCui** [comment]
The same request, please

**Comment by lvxiaxia** [comment]
The same request, please~

**Comment by ChenJingyuan91** [comment]
> The same request, please~

The dataset is no longer publicly available due to copyright issues.
